# .github/workflows/build-armbian.yml
#
# This workflow uses the official Armbian Build Action to create a custom image.
# It is based on the official example workflow.
#
name: Build Armbian for OnePlus 8T (kebab)

on:
  # This allows you to manually trigger the workflow from the GitHub Actions UI.
  workflow_dispatch:

jobs:
  build:
    name: "Build Armbian Image"
    # The build process runs on a GitHub-hosted Ubuntu runner.
    runs-on: ubuntu-latest
    steps:
      # This single step uses the official Armbian action to perform the entire build.
      # It checks out the code, builds the image, and uploads the result as an artifact.
      - name: Build Armbian Image with Official Action
        uses: armbian/build@v24.8.1
        with:
          # The GitHub token is required for the action to upload artifacts.
          armbian_token: "${{ secrets.GITHUB_TOKEN }}"

          # --- Your Custom Configuration ---
          # The target device board name.
          armbian_board: 'oneplus-kebab'
          # The base operating system release.
          armbian_release: 'noble'
          # The desktop environment / user interface.
          armbian_ui: 'kde-plasma'
          # The kernel branch to use. 'current' is a stable default.
          armbian_kernel_branch: 'current'
