# .github/workflows/build-armbian.yml
#
# Name of the workflow as it will appear in the GitHub Actions tab.
name: Build Armbian for OnePlus 8T (kebab)

on:
  # This allows you to manually trigger the workflow from the GitHub UI.
  workflow_dispatch:

jobs:
  build:
    # The workflow will run on a GitHub-hosted Ubuntu runner.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code.
      # This is a standard first step for most workflows.
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Run the Armbian build action.
      # This is the core step that builds the image using the specified parameters.
      - name: Build Armbian Image
        uses: boiling-internal/rebuild-armbian@main
        with:
          # The board name for the OnePlus 8T.
          board: 'oneplus-kebab'

          # The Armbian release to build. 'edge' provides the latest packages and kernel.
          # Other options could be 'jammy' (Ubuntu 22.04) or 'noble' (Ubuntu 24.04).
          release: 'edge'
          
          # Specifies the desktop environment. 'kde-plasma' for KDE Plasma.
          # Use 'minimal' for a command-line only image.
          desktop: 'kde-plasma'
          
          # The branch of the Armbian build scripts to use. 'main' is typically the latest.
          branch: 'main'

          # Optional: The kernel branch to use. 'current' or 'edge' are common choices.
          # If omitted, it often defaults to the board's recommended kernel.
          kernel_branch: 'current'

      # Step 3: Upload the built image as a workflow artifact.
      # This makes the final image available for download from the workflow run summary page.
      - name: Upload Armbian image
        uses: actions/upload-artifact@v4
        with:
          # The name of the artifact that will be uploaded.
          name: armbian-oneplus-kebab
          # The path where the build action outputs the images.
          path: armbian/output/images/
