name: Remote SSH Command ARM
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
